name: Deploy Vite.js application to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Set up PNPM
      - name: Set up `pnpm`
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      # Set up Node.js
      - name: Set up `node`
        uses: actions/setup-node@v4
        with:
          node-version: 23
          check-latest: true
          cache: "pnpm"
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      # Build application
      - name: Build application
        run: pnpm run build
      # Upload built artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: dist/
  deploy-to-gh-pages:
    needs: build-and-upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
